name: Web App CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Aditya@123
          POSTGRES_DB: health_check_db
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U postgres" --health-timeout=30s --health-interval=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Set up .env file
        run: echo "DB_NAME=health_check_db\nDB_USER=postgres\nDB_PASS=Aditya@12345\nDB_HOST=localhost\nDB_DIALECT=postgres\nPORT=8080" > .env

      - name: Wait for PostgreSQL to be ready
        run: sleep 10